const actions = {
  LOGGED_IN: "LOGGED_IN",
  LOGGED_OUT: "LOGGED_OUT",
  SET_DATA: "SET_DATA",
  LOADING: "LOADING",
  SET_ERROR: "SET_ERROR",
  UNSET_ERROR: "UNSET_ERROR",
  SET_API_ERROR: "SET_API_ERROR",
  UNSET_API_ERROR: "UNSET_API_ERROR",
};

export default actions;
